### ISSUE TITLE
Incompatible with newer node version

### ISSUE THREAD

**Issue by fumbleforce** [coagmano/meteor-stylus#9]
After upgrading meteor to 2.4, this package, or rather the stylus fork, is throwing circular dependency warnings.
Related to this issue
https://github.com/stylus/stylus/issues/2534

The issue is fixed in 0.54.8, while this project uses a fork of 0.54.5

```
(node:33648) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:674:11)
    at Object.get (internal/modules/cjs/loader.js:688:5)
    at Boolean.Node [as constructor] (/home/jorgen/.meteor/packages/coagmano_stylus/.2.0.0.sfu7pi.hqi0j++os+web.browser+web.browser.legacy+web.cordova/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/stylus/lib/nodes/node.js:42:23)
    at new Boolean (/home/jorgen/.meteor/packages/coagmano_stylus/.2.0.0.sfu7pi.hqi0j++os+web.browser+web.browser.legacy+web.cordova/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/stylus/lib/nodes/boolean.js:23:8)
    at Object.<anonymous> (/home/jorgen/.meteor/packages/coagmano_stylus/.2.0.0.sfu7pi.hqi0j++os+web.browser+web.browser.legacy+web.cordova/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/stylus/lib/nodes/index.js:57:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.Mp._compile (/tools/static-assets/server/runtime.js:78:21)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jorgen/.meteor/packages/coagmano_stylus/.2.0.0.sfu7pi.hqi0j++os+web.browser+web.browser.legacy+web.cordova/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/stylus/lib/lexer.js:13:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.Mp._compile (/tools/static-assets/server/runtime.js:78:21)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jorgen/.meteor/packages/coagmano_stylus/.2.0.0.sfu7pi.hqi0j++os+web.browser+web.browser.legacy+web.cordova/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/stylus/lib/parser.js:11:13)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.Mp._compile (/tools/static-assets/server/runtime.js:78:21)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jorgen/.meteor/packages/coagmano_stylus/.2.0.0.sfu7pi.hqi0j++os+web.browser+web.browser.legacy+web.cordova/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/stylus/lib/renderer.js:12:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.Mp._compile (/tools/static-assets/server/runtime.js:78:21)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.Mp.load (/tools/static-assets/server/runtime.js:35:31)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/jorgen/.meteor/packages/coagmano_stylus/.2.0.0.sfu7pi.hqi0j++os+web.browser+web.browser.legacy+web.cordova/plugin.compileStylusBatch.os/npm/node_modules/meteor/compileStylusBatch/node_modules/stylus/lib/stylus.js:11:16)

```

**Comment by fumbleforce** [comment]
I can confirm that updating stylus will fix it, though it requires us to also update the dependent stylus versions from the plugins.

**Comment by StorytellerCZ** [comment]
@jorgeer can you please provide a PR with the fix? This repo is part of [Hacktoberfest](hacktoberfest.digitalocean.com/) so it will count towards your PR count.
